lang_name: Español
read_full_post: Leer el artículo entero..
date_format: "%-d/%m/%Y"
recent_posts: Últimas entradas
rss_subscribe: '<a href="$url">suscríbase por RSS</a>'
no_translation: Lo siento, esta página no está disponible en español.
closeGallery: Cerrar galería
toggleMaximize: Maximizar
previousSlide: Imagen anterior
nextSlide: Imagen siguiente
download: Descargar
playVideo: Reproducir vídeo
mediaLoadingFailed: Ups... Error al cargar el contenido...
viewFullscreen: Activar pantalla completa
exitFullscreen: Desactivar pantalla completa
zoomIn: Aumentar
zoomOut: Disminuir
contactName: Nombre
contactEmail: Correo electrónico
contactMessage: Mensaje
contactSubmit: Enviar
